
/*
 * Copyright (c) 2022 船山信息 chuanshaninfo.com
 * The project is licensed under Mulan PubL v2.
 * You can use this software according to the terms and conditions of the Mulan
 * PubL v2. You may obtain a copy of Mulan PubL v2 at:
 *          http://license.coscl.org.cn/MulanPubL-2.0
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PubL v2 for more details.
 */

#pragma once

enum SharedPaintCodeType {
    CODE_SYSTEM_JOIN_TO_SERVER,
    CODE_SYSTEM_JOIN_TO_SUPERPEER,
    CODE_SYSTEM_RES_JOIN,
    CODE_SYSTEM_LEFT,
    CODE_SYSTEM_TCPSYN,
    CODE_SYSTEM_TCPACK,
    CODE_SYSTEM_CHANGE_SUPERPEER,
    CODE_SYSTEM_SYNC_REQUEST,
    CODE_SYSTEM_SYNC_START,
    CODE_SYSTEM_SYNC_COMPLETE,
    CODE_SYSTEM_VERSION_INFO,
    CODE_SYSTEM_CHANGE_NICKNAME,
    CODE_SYSTEM_CHAT_MESSAGE,
    CODE_SYSTEM_HISTORY_USER_LIST,
    CODE_UDP_SERVER_INFO,
    CODE_BROAD_PROBE_SERVER,
    CODE_BROAD_TEXT_MESSAGE,
    CODE_PAINT_SET_BG_IMAGE,
    CODE_PAINT_SET_BG_COLOR,
    CODE_PAINT_SET_BG_GRID_LINE,
    CODE_PAINT_CLEAR_BG,
    CODE_PAINT_CLEAR_SCREEN,
    CODE_PAINT_CREATE_ITEM,
    CODE_TASK_EXECUTE,
    CODE_WINDOW_RESIZE_MAIN_WND,
    CODE_WINDOW_RESIZE_CANVAS,
    CODE_WINDOW_RESIZE_WND_SPLITTER,
    CODE_WINDOW_CHANGE_CANVAS_SCROLL_POS,
    CODE_SCREENSHARE_CHANGE_RECORD_STATUS,
    CODE_SCREENSHARE_CHANGE_SHOW_STREAM,
    CODE_SCREENSHARE_RES_SHOW_STREAM,
    CODE_MAX,
};
